config/routes.rb
Rails.application.routes.draw do

  get 'bases/index'

  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
  
  # ログイン機能
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  # 出勤中社員一覧
  get '/working_users', to: 'users#working_users'
  
  # 拠点resources
  resources :bases
  

  
  resources :users do 
    collection do
      get '/search', to: 'users#search' 
      post :import
    end
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get 'attendances/attendance_index'
      patch 'user_index_edit'
      get 'attendance_log'
      #残業申請　上長
      get 'overtime_admin'
      patch 'overtime_admin_update'
      #１ヶ月分の勤怠情報申請
      patch 'one_month_application'
      get 'modal_one_month'
      patch 'admin_modal_one_month'
      # 勤怠変更申請
      get 'edit_superior'
      patch 'edit_superior_update'
      # 勤怠ログ
      get 'at_log'
    end
    resources :attendances, only: [:update] do
      get 'overtime'
      patch 'overtime_application'
      collection do
      end
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  
  # 「remember_token」という仮想の属性を作成します。
  attr_accessor :remember_token
  before_save { self.email = email.downcase }

  validates :name,  presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true    
  validates :department, length: { in: 2..30 }, allow_blank: true
  validates :basic_time, presence: true
  validates :work_time, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validates :employee_number, presence: true
  validates :u_id, presence: true

  # 渡された文字列のハッシュ値を返します。
  def User.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返します。
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためハッシュ化したトークンをデータベースに記憶します。
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # トークンがダイジェストと一致すればtrueを返します。
  def authenticated?(remember_token)
    # ダイジェストが存在しない場合はfalseを返して終了します。
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄します。
  def forget
    update_attribute(:remember_digest, nil)
  end
  

  def self.import(file)
    if file.present? 
      CSV.foreach(file.path, headers: true) do |row|
        # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
        user = find_by(id: row["id"]) || new
        # CSVからデータを取得し、設定する
        user.attributes = row.to_hash.slice(*updatable_attributes)
        # 保存する
        user.save!
      end
    end
  end

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["name", "email", "department", "employee_number", "u_id", "basic_time", "designated_work_start_time", "designated_work_end_time", "superior", "admin", "password"]
  end
  
  


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info, :user_index_edit, :attendance_log]
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:index, :destroy, :edit_basic_info, :update_basic_info]
  before_action :set_one_month, only: :show
  before_action :admin_or_correct_user_or_superior, only: [:show, :edit, :update]
  before_action :admin_not, only: :show
  
  
  def index
    @users = set_search.paginate(page: params[:page]).includes(:attendances)
    @user = User.new
  end
  
  def show
    @attendance = Attendance.find(params[:id])
    @worked_sum = @attendances.where.not(started_at: nil).count
    @overtime_sum = Attendance.where.not(overtime_application: nil)
    @app = User.joins(:attendances).where.not(id: current_user.id).where(attendances: { overtime_application: current_user.name }).count
    @app_sub = User.joins(:attendances).where(attendances: {change_button: 0}).where(attendances: {overtime_application: current_user.name}).where.not(id: current_user.id).count 
    @name_ins = User.joins(:attendances).where.not(id: current_user.id).where(superior: true).pluck(:name)
    @one_month_app = User.joins(:attendances).where(attendances: { app_name: current_user.name }).where.not(id: current_user.id).where(attendances: {one_change_b: 0}).count
    @edit_at_count = Attendance.joins(:user).where(edit_app_n: current_user.name).where.not(edit_finish: nil).where.not(user_id: current_user.id).where(edit_change_b: "0").count
  end
  
  def new
    # ユーザーオブジェクトを生成し、インスタンス変数に代入します。
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      # 保存成功後、ログインします。
      log_in @user
      flash[:success] = '新規作成に成功しました。'
      redirect_to @user
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました"
      redirect_to @user
    else
      render :edit
    end
  end
  
  def update_user
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました"
      redirect_to current_user
    else
      render :index
    end
  end
  
  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end
  
  def search
    @users = set_search.paginate(page: params[:page])
  end  
  
  def import
      # fileはtmpに自動で一時保存される
    if User.import(params[:file])
      flash[:success] = "CSVファイルを読み込みました。"
      redirect_to users_url 
    else
      flash[:danger] = "CSVファイルを読み込めませんでした。"
      redirect_to users_url
    end
  end
  
  def working_users
    @users = User.all.includes(:attendances)
  end  
  
  def edit_basic_info
  end
  
  def update_basic_info
    if @user.update_attributes(basic_info_params)
      flash[:success] = "#{@user.name}の基本情報を更新しました"
    else
      flash[:danger] = "#{@user.name}の更新は失敗しました<br>" + @user.errors.full_messages.join("<br>")
    end
    redirect_to users_url
  end
  
  def user_index_edit
    @users = User.all
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました"
      redirect_to users_url
    else
      flash[:danger] = "ユーザー情報を更新できませんでした。"
      redirect_to users_url
    end
  end
  
  def overtime_admin
    @user = User.find(params[:id])
    @users = User.joins(:attendances).where.not(attendances: {overtime: nil}).where.not(id: current_user).where(attendances: { overtime_application: current_user.name }).where(attendances: {change_button: 0}).distinct(:name)
    @user_judge = User.joins(:attendances).where(attendances: {change_button: 0}).where(attendances: {overtime_application: current_user.name}).where.not(id: current_user.id).count
    @attendances = Attendance.joins(:user).where(overtime_application: current_user.name)
    
  end
  
  def overtime_admin_update
    @user = User.find(params[:id])
    @users = User.joins(:attendances).where.not(attendances: {overtime: nil}).where.not(id: current_user).where(attendances: { overtime_application: current_user.name })
    @user_judge = User.joins(:attendances).where(attendances: {change_button: 0}).where(attendances: {overtime_application: current_user.name}).where.not(id: current_user.id).count
    @attendances = Attendance.joins(:user).where.not(overtime: nil).where.not(user_id: current_user.id).where(overtime_application: current_user.name)
    ActiveRecord::Base.transaction do
      if superior_invalid
        Attendance.attendance_update(admin_params)
        flash[:success] = "ユーザーからの申請を更新しました。"
        redirect_to @user
      else
        flash[:info] = "一部の情報を「なし」か「申請中」で更新しました。今一度ご確認ください。"
        redirect_to @user
      end
    end
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = "変更ボタンを押していないか確認してください。"
    redirect_to @user
  end
  
  def one_month_application
    @user = User.find(params[:id])
    @attendance = Attendance.find(params[:id])
    ActiveRecord::Base.transaction do
      if Attendance.one_month_up(one_month_application_params)
          flash[:success] = "１ヶ月分の勤怠申請を送信しました。"
          redirect_to @user
      else
        flash[:info] = "すでに申請を送ってありますので、承認をお待ちください。"
        redirect_to @user
      end
    end
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = "変更ボタンを押していないか確認してください。"
    redirect_to @user
  end
  
  def modal_one_month
    @user = User.find(params[:id])
    @users = User.joins(:attendances).where.not(id: current_user).where(attendances: { app_name: current_user.name }).where(attendances: { one_change_b:  "0"}).distinct(:name)
    @one_month = Attendance.joins(:user).where(app_name: current_user.name ).where.not(user_id: current_user.id).where(one_change_b: 0)    
  end
  
  def admin_modal_one_month
    @user = User.find(params[:id])
    ActiveRecord::Base.transaction do
      if one_invalid 
        Attendance.admin_modal_one_up(admin_one_params)
        flash[:success] = "ユーザーからの申請を更新しました。"
        redirect_to @user
      else
        flash[:info] = "一部の情報を「なし」か「申請中」で更新しました。今一度ご確認ください。"
        redirect_to @user
      end
    end
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = "変更ボタンを押していないか確認してください。"
    redirect_to @user
  end
  
  def edit_superior
    @user = User.find(params[:id])
    @users = User.joins(:attendances).where.not(attendances: {edit_finish: nil}).where(attendances: {edit_app_n: current_user.name}).where.not(id: current_user.id).distinct(:name)
    @attendances = Attendance.joins(:user).where.not(edit_finish: nil).where(edit_app_n: current_user.name).where.not(user_id: current_user.id).where(edit_change_b: "0")
  end
  
  def edit_superior_update
    @user = User.find(params[:id])
    ActiveRecord::Base.transaction do
      if edit_invalid
        Attendance.edit_superior_d(edit_params)
        flash[:success] = "ユーザーからの申請を更新しました。"
        redirect_to @user
      else
        flash[:info] = "一部の情報を「なし」か「申請中」で更新しました。今一度ご確認ください。"
        redirect_to @user
      end
    end
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = "一部の情報を「なし」か「申請中」で更新しました。今一度ご確認ください。"
    redirect_to @user
  end
  
  def at_log
    @user = User.find(params[:id])
    @attendance = Attendance.find(params[:id])
    @attendances = Attendance.joins(:user).where(edit_app_s: "1").where(user_id: current_user.id)
  end
  
  private
  
    def user_params
      params.require(:user).permit(:name, :email, :department, :password, :password_confirmation, :employee_number, :u_id, :basic_time, :designated_work_start_time, :designated_work_end_time, :superior)
    end
    
    #残業申請：上長承認モーダルの更新strong_params
    def admin_params
      params.require(:user).permit(attendances: [:app_number, :change_button])[:attendances]
    end
    
    #１ヶ月分の勤怠申請：ユーザー側の申請strong_params
    def one_month_application_params
      params.require(:user).permit(attendances: [:app_name])[:attendances]
    end
    
    #１ヶ月分の勤怠申請：上長側の申請strong_params
    def admin_one_params
      params.require(:user).permit(attendances: [:one_app_n, :one_change_b])[:attendances]
    end
    
    #　勤怠変更の申請：上長ユーザーの申請strong_params
    def edit_params
      params.require(:user).permit(attendances: [:edit_note, :edit_app_s, :edit_change_b])[:attendances]
    end
    
    def set_search
      if params[:user].present? && params[:user][:name]
        User.where('name LIKE ?', "%#{params[:user][:name]}%")
      else
        User.all
      end
    end
    

    
    def basic_info_params
      params.require(:user).permit(:department, :basic_time, :work_time)
    end
    
    # 管理権限者、または現在ログインしているユーザーを許可します。
    def admin_or_correct_user_or_superior
      @user = User.find(params[:user_id]) if @user.blank?
      unless current_user?(@user) || current_user.admin? || current_user.superior?
        flash[:danger] = "編集権限がありません。"
        redirect_to(root_url)
      end  
    end
    
    def admin_not
      @user = User.find(params[:id])
      if current_user.admin?
        flash[:success] = "管理者の勤怠表は存在しません。"
        redirect_to(root_url)
      end
    end
    
    def superior_invalid
      superior = true
      admin_params.each do |id, admin_params|
        if admin_params[:change_button] == "1" && admin_params[:app_number] == "1" || admin_params[:app_number] == "2"
          superior = true
          next
        elsif admin_params[:change_button] == "1" && admin_params[:app_number] == "0" || admin_params[:app_number] == "3"
          superior = false
          break
        elsif admin_params[:change_button] == "0"
          superior = false
          break
        elsif admin_params[:app_number].nil?
          superior = false
          break
        end
      end
      return superior
    end  
    
    def one_invalid
      one_admin = true
      admin_one_params.each do |id, admin_one_params|

app/helpers/users_helper.rb
module UsersHelper
  
  # 勤怠基本情報を指定のフォーマットで返します。 
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
  
     
  
end

app/views/users/_modal_one_month.html.erb
<div class="container">
  <div class="modal-dialog modal-lg modal-dialog-center">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_with(model: @user, url: admin_modal_one_month_user_path(@user, @attendance), local: true, method: :patch) do |f| %>
          <% @users.each do |user| %>
            <table class="table table-bordered table-striped table-condensed">
              <h1>【<%= user.name %>】</h1>
              <thead id="table-attendances">
                <tr>
                  <th>年 / 月</th>
                  <th>指示確認㊞</th>
                  <th>変更</th>
                  <th>勤怠を確認する</th>
                  </tr>
              </thead>
              <% @one_month.each do |one| %>
                <% if one.user.id == user.id %>
                  <tbody class="center">
                    <tr>
                      <td><%= l(one.worked_on, format: :middle) %></td>
                      <%= f.fields_for "attendances[]", one do |ad| %>
                        <td><%= ad.select :one_app_n, [['なし', 0], ['承認', 1], ['否認', 2], ['申請中', 3]], { include_blank: true, selected: 0 } %></td>
                        <td><%= ad.check_box :one_change_b,:as => :boolean, checked: false %></td>
                      <% end %>
                      <td><%= link_to "確認する", user_path(user), class: "btn btn-primary btn-sm" %></td>
                    </tr>
                  </tbody>
                <% end %>  
              <% end %>
            </table>
          <% end %>
          <div class="center">
            <%= f.submit "変更を送信する", class: "btn btn-primary btn-lg" %>
          </div><br>
        <% end %>
      </div>          
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1><%= @user.name %></h1>

  <div>
    <table class="table table-bordered table-condensed" id="table-attendances">
      <tr class="user-table">
        <td>
          <% if current_user.id == @user.id %>
            <%= link_to "←️", user_path(date: @first_day.prev_month), class: "table-show btn btn-sm btn-default btn-primary" %> 
          <% end %>
          <%= l(@first_day, format: :middle) %>  勤怠管理表 
          <% if current_user.id == @user.id %>
            <%= link_to "→", user_path(date: @first_day.next_month), class: "btn btn-sm btn-default  btn-primary" %> 
          <% end %>
        </td>
        <td colspan="2" class="center">
                          指定勤務開始時間 : <%= l(@user.designated_work_start_time, format: :hour) %>:<%= l(@user.designated_work_start_time, format: :minit) %>　<br>
                          指定勤務終了時間 : <%= l(@user.designated_work_end_time, format: :hour) %>:<%= l(@user.designated_work_end_time, format: :minit) %>
        </td>
        <td colspan="2">基本時間　<%= format_basic_info(@user.basic_time) %></td>
        <td>初日　<%= l(@first_day, format: :short) %></td>
      </tr>
  
      <tr class="user-table">
        <td>所属　<%= @user.department.present? ? @user.department : "未所属" %></td>
        <td>氏名　<%= @user.name %></td>
        <td>コード</td>
        <td><%= @user.employee_number %></td>
        <td>出勤日数　<%= @worked_sum %>日</td>
        <td>締め　<%= l(@last_day, format: :short) %></td>
      </tr>
    </table>
  </div>
  
  <div>
    <% if current_user.id == @user.id %>
      <% if @user.admin || @user.superior %>
        <% if @one_month_app > 0 %>
          <div><%= link_to "【所属長承認申請のお知らせ】", modal_one_month_user_path(@user), remote: true, class: 'overtime-application' %>
            <div class="overtime-div"><%= @one_month_app %>件の通知があります。</div>
          </div><br>
        <% else %>
          <div>【所属長承認申請のお知らせ】</div><br>
        <% end %>
        
        <% if @edit_at_count > 0 %>
          <div><%= link_to "【勤怠変更申請のお知らせ】", edit_superior_user_path(@user), remote: true, class: 'overtime-application' %>
            <div class="overtime-div"><%= @edit_at_count %>件の通知があります。</div>
          </div><br>
        <% else %>
          <div>【勤怠変更申請のお知らせ】</div><br>
        <% end %>
        
        <% if @app_sub > 0 %>
          <div><%= link_to "【残業申請のお知らせ】", overtime_admin_user_path(@user), remote: true, class: 'overtime-application' %> 
            <div class="overtime-div"><%= @app_sub %>件の通知があります</div>
          </div>
        <% else %>
          <p>【残業申請のお知らせ】</p>
        <% end %>
      <% end %>
    <% end %>
  </div><br>
  
  <% if current_user.id == @user.id %>
    <div class="btn-users-show btn-attendance-a">
      <%= link_to "勤怠の編集", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-default  btn-primary" %>
      <%= link_to "CSVの出力", user_path(format: :csv), class: "btn btn-primary" %> 
    </div>
    <div class="btn-users-show">
      <%= link_to "勤怠修正ログ（承認済み）", at_log_user_path(@user), class: "btn btn-default  btn-primary" %>
    </div>
  <% end %>
  
  <div>
    <table class="table table-bordered table-condensed table-hover" id="table-attendances">
      <thead>
        <tr>
          <th rowspan="3">残業申請</th>
          <th rowspan="3">日付</th>
          <th rowspan="3">曜日</th>
          <th colspan="8">【実績】</th>
          <th colspan="5">【所定外勤務】</th>
        </tr>
        <tr>
          <th colspan="3">出社</th>
          <th colspan="3">退社</th>
          <th rowspan="2">在社時間</th>
          <th rowspan="2">備考</th>
          <th colspan="2">終了予定時間</th>
          <th rowspan="2">時間外時間</th>
          <th rowspan="2">業務処理内容</th>
          <th rowspan="2">指示者確認印</th>
        </tr>
        <tr>
          <th>時</th>
          <th>分</th>
          <th></th>
          <th>時</th>
          <th>分</th>
          <th></th>
          <th>時</th>
          <th>分</th>
        </tr> 
      </thead>
  
      <tbody>
        <% @attendances.each do |day| %>
          <tr>
            <td>
              <% if current_user.id == @user.id %>
                <a><%= link_to "残業申請", user_attendance_overtime_path(@user, day), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#overtime', class: 'btn btn-default  btn-primary'} %></a>
              <% end %>
            </td>
            <td><%= l(day.worked_on, format: :short) %></td>
            <td>
              <% if day.worked_on.wday == 6 %>
                <font color="blue">土</font>
              <% elsif day.worked_on.wday == 0 %>
                <font color="red">日</font>
              <% elsif day.worked_on.wday == 1 %>
                <font color="black">月</font>
              <% elsif day.worked_on.wday == 2 %>
                <font color="black">火</font>
              <% elsif day.worked_on.wday == 3 %>
                <font color="black">水</font>
              <% elsif day.worked_on.wday == 4 %>
                <font color="black">木</font>
              <% elsif day.worked_on.wday == 5 %>
                <font color="black">金</font>
              <% end %> 
            </td>
            <% if day.edit_finish.present? && day.edit_change_b == true && day.edit_app_s == "1" %>
              <td><%= l(day.edit_start, format: :hour) if day.edit_start.present? %></td>
              <td><%= l(day.edit_start.floor_to(15.minutes), format: :minit) if day.edit_start.present? %></td>
              <td>
                <% if day.worked_on == Date.current && day.started_at.blank? %>
                  <% if current_user.id == @user.id %>
                    <%= button_to "出社", user_attendance_path(@user, day), method: :patch, class: "btn btn-default btn-block btn-primary btn-attendance" %>
                  <% end %>
                <% end %>            
              </td>
              <td><%= l(day.edit_finish, format: :hour) if day.edit_finish.present? %></td>
              <td><%= l(day.edit_finish.floor_to(15.minutes), format: :minit) if day.edit_finish.present? %></td>
              <td>
                <% if day.worked_on == Date.current && day.started_at.present? && day.finished_at.blank? %>
                  <% if current_user.id == @user.id %>
                    <%= button_to "退社", user_attendance_path(@user, day), method: :patch, class: "btn btn-default btn-block btn-primary btn-attendance" %>
                  <% end %>
                <% end %>             
              </td>  
            <% else %>
              <td><%= l(day.started_at, format: :hour) if day.started_at.present? %></td>
              <td><%= l(day.started_at.floor_to(15.minutes), format: :minit) if day.started_at.present? %></td>
              <td>
                <% if day.worked_on == Date.current && day.started_at.blank? %>
                  <% if current_user.id == @user.id %>
                    <%= button_to "出社", user_attendance_path(@user, day), method: :patch, class: "btn btn-default btn-block btn-primary btn-attendance" %>
                  <% end %>
                <% end %>            
              </td>
              <td><%= l(day.finished_at, format: :hour) if day.finished_at.present? %></td>
              <td><%= l(day.finished_at.floor_to(15.minutes), format: :minit) if day.finished_at.present? %></td>
              <td>
                <% if day.worked_on == Date.current && day.started_at.present? && day.finished_at.blank? %>
                  <% if current_user.id == @user.id %>
                    <%= button_to "退社", user_attendance_path(@user, day), method: :patch, class: "btn btn-default btn-block btn-primary btn-attendance" %>
                  <% end %>
                <% end %>             
              </td>
            <% end %>
            <td>
             <% if day.edit_start.present? && day.edit_finish.present? && day.edit_change_b == true && day.edit_next_d == true && day.edit_app_s == "1" %>
               <%= edit_next_times(day.edit_start, day.edit_finish) %>
             <% elsif day.edit_start.present? && day.edit_finish.present? && day.edit_change_b == true && day.edit_app_s == "1" && day.edit_next_d == false %>
               <%= edit_not_next(day.edit_start, day.edit_finish) %>
             <% elsif day.started_at.present? && day.finished_at.present? %>
                <%= str_times = working_times(day.started_at, day.finished_at) %>
                <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
              <% end %>            
            </td>
            <td><%= day.edit_note %></td>
            <% if day.change_button == "1" && day.app_number == "1" %>
              <td><%= l(day.overtime, format: :hour) if day.overtime.present? %></td>
              <td><%= l(day.overtime.floor_to(15.minutes), format: :minit) if day.overtime.present? %></td>
              <td>
                <% if day.check_botan == true && day.overtime.present? %>
                  <%= overtimes_true(day.overtime.strftime("%T"), @user.designated_work_end_time.strftime("%T")) %>
                  
                <% elsif day.check_botan == false && day.overtime.present? %>
                  <%= overtimes_false(day.overtime.strftime("%T"), @user.designated_work_end_time.strftime("%T")) %>
                  
                <% end %>
              </td>
              <td><%= day.overtime_note %></td>
            <% else %>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
            <% end %>
            <td>
              <% if day.change_button == "0" && day.overtime.present? || day.app_number == "3" && day.app_number == "0" %>
                <%= day.overtime_application %>に残業申請中<br>
              <% elsif day.app_number == "1" && day.change_button == "1" %>
                <%= day.overtime_application %>から残業承認済<br>
              <% elsif day.app_number == "2" && day.change_button == "1" %>  
                 <%= day.overtime_application %>から残業否認<br>
              <% end %>
              <% if day.edit_change_b == false && day.edit_finish %> 
                <%= day.edit_app_n %>に勤怠申請中<br>
              <% elsif day.edit_change_b == true && day.edit_app_s == "1" %>
                <%= day.edit_app_n %>から申請が承認されました。<br>
              <% elsif day.edit_change_b == true && day.edit_app_s == "2" %>
                <%= day.edit_app_n %>から申請を否認されました。
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
      
      <tfooter>
        <tr>
          <td></td>
          <td colspan="2"></td>
          <td colspan="6"></td>
          <td><%= format("%.2f", @total_working_times.to_f) %></td>
          <td colspan="5"></td>
          <% if current_user == @user %>
            <td>
              <% @attendances.where(worked_on: @first_day).each do |attendance| %> 
                <%= form_with(model: @user, url: one_month_application_user_path(@user, @attendance), local: true) do |f| %> 
                  <% if attendance.app_name.blank? %>
                    所属長承認　未<br><br>
                  <% elsif attendance.one_change_b == "0" %>
                    <%= attendance.app_name %>に申請中<br>
                  <% elsif attendance.one_app_n == "2" && attendance.one_change_b == "1" %>
                    <%= attendance.app_name %>様から申請を否認されました<br>
                  <% elsif attendance.one_app_n == "1" && attendance.one_change_b == "1" %>
                    <%= attendance.app_name %>様から申請を承認されました<br>
                  <% end %>
                  <%= f.fields_for "attendances[]", attendance do |t| %>
                    <% if attendance.one_change_b == "0" %>
                      <%= t.select :app_name, User.where.not(id: current_user.id).where(superior: true).pluck(:name) %><br><br>
                      <%= t.submit "申請", class: "btn btn-default btn-primary form-control" %>
                    <% elsif attendance.one_app_n == "1" && attendance.one_change_b == "1" %>
                      <%= t.select :app_name, [["", 0]] %><br><br>
                      <%= link_to "申請済", "#", class: "btn btn-default btn-primary form-control" %>
                    <% elsif attendance.one_app_n == "2" && attendance.one_change_b == "1" %>
                      <%= t.select :app_name, [["", 0]] %><br><br>
                      <%= link_to "申請済", "#", class: "btn btn-default btn-primary form-control" %>
                    <% end %>
                  <% end %>
                <% end %>
              <% end %>
            </td>
          <% else %>
            <td></td>
          <% end %>
        </tr>
      </tfooter>
      
    </table>
  </div>

<div id="overtime" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="overtime_admin" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="modal_one_month" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="edit_superior" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>