config/routes.rb
Rails.application.routes.draw do

  get 'bases/index'

  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
  
  # ログイン機能
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  # 出勤中社員一覧
  get '/working_users', to: 'users#working_users'
  
  # 拠点resources
  resources :bases
  

  
  resources :users do 
    collection do
      get '/search', to: 'users#search' 
      post :import
    end
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get 'attendances/attendance_index'
      patch 'user_index_edit'
      get 'attendance_log'
      #残業申請　上長
      get 'overtime_admin'
      patch 'overtime_admin_update'
      #１ヶ月分の勤怠情報申請
      patch 'one_month_application'
      get 'modal_one_month'
      patch 'admin_modal_one_month'
      # 勤怠変更申請
      get 'edit_superior'
      patch 'edit_superior_update'
      # 勤怠ログ
      get 'at_log'
    end
    resources :attendances, only: [:update] do
      get 'overtime'
      patch 'overtime_application'
      collection do
      end
    end
  end

end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user

  validates :worked_on, presence: true
  validates :note, length: { maximum: 50 }
 
  # 出勤時間が存在しない場合、退勤時間は無効
  validate :finished_at_is_invalid_without_a_started_at
  # 出勤・退勤時間どちらも存在する時、出勤時間より早い退勤時間は無効
  validate :started_at_than_finished_at_fast_if_invalid

  def finished_at_is_invalid_without_a_started_at
    errors.add(:started_at, "が必要です") if started_at.blank? && finished_at.present?
  end

  def started_at_than_finished_at_fast_if_invalid
    if started_at.present? && finished_at.present?
      errors.add(:started_at, "より早い退勤時間は無効です") if started_at > finished_at
    end
  end
  
  def self.attendance_update(admin_params)
    admin_params.to_h.map do |id, admin_params|
      superior = self.find(id)
      superior.update_attributes!(admin_params)
    end
  end
  
  def self.one_month_up(one_month_application_params)
    one_month_application_params.to_h.map do |id, one_month_application_params|
      one_month = self.find(id)
      one_month.update_attributes!(one_month_application_params)
    end
  end
  
  def self.admin_modal_one_up(admin_one_params)
    admin_one_params.to_h.map do |id, admin_one_params|
      admin_one = self.find(id)
      admin_one.update_attributes!(admin_one_params)
    end
  end
  
  def self.edit_superior_d(edit_params)
    edit_params.to_h.map do |id, edit_params|
      edit_superior = self.find(id)
      edit_superior.update_attributes!(edit_params)
    end
  end
  
end

app/helpers/attendances_helper.rb
module AttendancesHelper
  
  def attendance_state(attendance)
    # 受け取ったAttendanceオブジェクトが当日と一致するか評価します。
    if Date.current == attendance.worked_on
      return '出勤' if attendance.started_at.nil?
      return '退勤' if attendance.finished_at.nil?
    end
    # どれにも当てはまらなかった場合はfalseを返します。
    false
  end
  
  # 出勤時間と退勤時間を受け取り、在社時間を計算して返します。
  def working_times(start, finish)
    format("%.2f", (((finish.floor_to(15.minutes) - start.floor_to(15.minutes)) / 60) / 60.0))
  end
  
  #翌日機能を入れた勤怠変更の計算
  def edit_next_times(start, finish)
    format("%.2f", (((finish.floor_to(15.minutes) - start.floor_to(15.minutes)) / 60) / 60.0) + 24)
  end
  
  def edit_not_next(start, finish)
    format("%.2f", (((finish.floor_to(15.minutes) - start.floor_to(15.minutes)).to_f / 60) / 60))
  end
  
  def attendances_invalid?
    attendances = true
    attendances_params.each do |id, item|
      if item[:started_at].blank? && item[:finished_at].blank?
        next
      elsif item[:started_at].blank? || item[:finished_at].blank?
        attendances = false
        break
      elsif item[:started_at] > item[:finished_at]
        attendances = false
        break
      end
    end
    return attendances
  end
  
  def edit_invalid?
    superior = true
    attendances_params.each do |id, item|
      if item[:edit_start].blank? && item[:edit_finish].blank?
        next
      elsif item[:edit_start].blank? || item[:edit_finish].blank?
        superior = false
        break 
      elsif item[:edit_started] > item[:edit_finish]
        attendances = false
        break
      end
    end
    return superior
  end
  
  def check_judge
      if @attendance.check_botan == true 
        @attendance.worked_on = @attendance.worked_on
      elsif @attendance.check_botan == false 
        @attendance.worked_on = @attendance.worked_on
      end
  end 
  
  
  
  
  
  def overtimes_true(overtime, designated_work_end_time)
    format("%.2f", (((overtime.to_time.floor_to(15.minutes) - designated_work_end_time.to_time.floor_to(15.minutes)).to_f / 60) / 60) + 24)
  end
  
  def overtimes_false(overtime, designated_work_end_time)
    format("%.2f", (((overtime.to_time.floor_to(15.minutes) - designated_work_end_time.to_time.floor_to(15.minutes)).to_f / 60) / 60) - 0)
  end

  # 勤怠基本情報を指定のフォーマットで返します。 
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
  
end

app/views/attendances/_overtime.html.erb
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '更新') %>
<div class="container">
    <%= form_with(model: @attendance, url: user_attendance_overtime_application_path(@user, @attendance), local: true, method: :patch) do |f| %>
      <div class="modal-dialog modal-lg modal-dialog-center">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <h1 class="modal-title">【残業申請】</h1>
          </div>
          <div class="modal-body">
                <table class="table table-bordered table-striped table-condensed">
                  <thead>
                    <tr>
                      <th>日付</td>
                      <th>曜日</td>
                      <th>終了予定時間</td>
                      <th>翌日</td>
                      <th>業務処理内容</td>
                      <th>指示確認㊞</td>
                    </tr>
                  </thead>
                  <tbody class="center">
                    <tr>
                      <td><%= l(@attendance.worked_on, format: :short) %></td>
                      <td>
                        <% if @attendance.worked_on.wday == 6 %>
                          <font color="blue">土</font>
                        <% elsif @attendance.worked_on.wday == 0 %>
                          <font color="red">日</font>
                        <% elsif @attendance.worked_on.wday == 1 %>
                          <font color="black">月</font>
                        <% elsif @attendance.worked_on.wday == 2 %>
                          <font color="black">火</font>
                        <% elsif @attendance.worked_on.wday == 3 %>
                          <font color="black">水</font>
                        <% elsif @attendance.worked_on.wday == 4 %>
                          <font color="black">木</font>
                        <% elsif @attendance.worked_on.wday == 5 %>
                          <font color="black">金</font>
                        <% end %> 
                      </td>
      
                      <td><%= f.time_select :overtime, discard_year: true, discard_month: true, selected: @attendance.worked_on %></td>
                      <td><%= f.check_box :check_botan, :as => :boolean, checked: false %></td>
                      <td><%= f.text_field :overtime_note, class: "form-control" %></td>
                      <td><%= f.select :overtime_application, @superior, include_blank: true %></td>
                    </tr>
                  </tbody>
                </table> 
          </div>
          <div class="modal-footer">
            <%= f.submit "変更を送信する", class: "btn  btn-primary form-control" %>
          </div>
        </div>
      </div>
    <% end %>
</div>

app/views/attendances/edit_one_month.html.erb
<% provide(:title, @user.name) %>
<%= form_with(model: @user, url: attendances_update_one_month_user_path(date: @first_day), local: true, method: :patch) do |f| %>
  <div>
    <h1>勤怠編集画面</h1>
    <table class="s-tbl table table-bordered table-condensed table-hover" id="table-attendances">
      <thead>
        <tr>
          <th>日付</th>
          <th>曜日</th>
          <th>出勤時間</th>
          <th>退勤時間</th>
          <th>翌日</th>
          <th>在社時間</th>
          <th colspan="3">備考</th>
          <th colspan="3">指示者確認㊞</th>
        </tr>
      </thead>
      <tbody>
      <% @attendances.each do |day| %>
        <%= f.fields_for "attendances[]", day do |attendance| %>
          <tr>
            <td><%= l(day.worked_on, format: :short) %></td>
            <td>
              <% if day.worked_on.wday == 6 %>
                <font color="blue">土</font>
              <% elsif day.worked_on.wday == 0 %>
                <font color="red">日</font>
              <% elsif day.worked_on.wday == 1 %>
                <font color="black">月</font>
              <% elsif day.worked_on.wday == 2 %>
                <font color="black">火</font>
              <% elsif day.worked_on.wday == 3 %>
                <font color="black">水</font>
              <% elsif day.worked_on.wday == 4 %>
                <font color="black">木</font>
              <% elsif day.worked_on.wday == 5 %>
                <font color="black">金</font>
              <% end %>
            </td>
            <% if current_user && (Date.current < day.worked_on) %>
              <td><%= attendance.time_field :edit_start, readonly: true, class: "form-control" %></td>
              <td><%= attendance.time_field :edit_finish, readonly: true, class: "form-control" %></td>
            <% else %>
              <td><%= attendance.time_field :edit_start, class: "form-control" %></td>
              <td><%= attendance.time_field :edit_finish, class: "form-control" %></td>
            <% end %>
            <td><%= attendance.check_box :edit_next_d,:as => :boolean, checked: false %></td>
            <td>
              <% if day.edit_start.present? && day.edit_finish.present? && day.edit_change_b == true && day.edit_next_d == true && day.edit_app_s == "1" %>
               <%= edit_next_times(day.edit_start, day.edit_finish) %>
             <% elsif day.edit_start.present? && day.edit_finish.present? && day.edit_change_b == true && day.edit_app_s == "1" %>
               <%= edit_not_next(day.edit_start, day.edit_finish) %>
             <% elsif day.started_at.present? && day.finished_at.present? %>
                <%= str_times = working_times(day.started_at, day.finished_at) %>
                <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
              <% end %> 
            </td>
            <td colspan="3"><%= attendance.text_field :note, class: "form-control" %></td>
            <td colspan="3"><%= attendance.select :edit_app_n, User.where(superior: true).where.not(id: current_user.id).pluck(:name),include_blank: true  %></td>
          </tr>
        <% end %>
      <% end %>
      
      </tbody>
    </table>
  </div>
  
  <div class="center">
    <%= link_to "キャンセル", user_path(date: @first_day), class: "btn btn-lg btn-default" %>
    <%= f.submit "編集を保存する", class: "btn btn-lg btn-default" %>
  </div>
<% end %>

app/views/attendances/overtime.js.erb
$("#overtime").html("<%= escape_javascript(render 'overtime') %>");
$("#overtime").modal("show");